// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidAmount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BidAmount     int64                  `protobuf:"varint,3,opt,name=bid_amount,json=bidAmount,proto3" json:"bid_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidAmount) Reset() {
	*x = BidAmount{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidAmount) ProtoMessage() {}

func (x *BidAmount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidAmount.ProtoReflect.Descriptor instead.
func (*BidAmount) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *BidAmount) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BidAmount) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BidAmount) GetBidAmount() int64 {
	if x != nil {
		return x.BidAmount
	}
	return 0
}

type BidAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidAck) Reset() {
	*x = BidAck{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidAck) ProtoMessage() {}

func (x *BidAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidAck.ProtoReflect.Descriptor instead.
func (*BidAck) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

func (x *BidAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *BidAck) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AuctionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HighestBid    int64                  `protobuf:"varint,1,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	Winner        int64                  `protobuf:"varint,2,opt,name=winner,proto3" json:"winner,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionResult) Reset() {
	*x = AuctionResult{}
	mi := &file_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionResult) ProtoMessage() {}

func (x *AuctionResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionResult.ProtoReflect.Descriptor instead.
func (*AuctionResult) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2}
}

func (x *AuctionResult) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *AuctionResult) GetWinner() int64 {
	if x != nil {
		return x.Winner
	}
	return 0
}

func (x *AuctionResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{3}
}

type ReplicaUpdate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Timestamp         int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	HighestBidder     int64                  `protobuf:"varint,2,opt,name=highest_bidder,json=highestBidder,proto3" json:"highest_bidder,omitempty"`
	HighestBid        int64                  `protobuf:"varint,3,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	AuctionFinished   bool                   `protobuf:"varint,4,opt,name=auction_finished,json=auctionFinished,proto3" json:"auction_finished,omitempty"`
	RequestIdentifier int64                  `protobuf:"varint,5,opt,name=request_identifier,json=requestIdentifier,proto3" json:"request_identifier,omitempty"`
	Response          *BidAck                `protobuf:"bytes,6,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReplicaUpdate) Reset() {
	*x = ReplicaUpdate{}
	mi := &file_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaUpdate) ProtoMessage() {}

func (x *ReplicaUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaUpdate.ProtoReflect.Descriptor instead.
func (*ReplicaUpdate) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicaUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ReplicaUpdate) GetHighestBidder() int64 {
	if x != nil {
		return x.HighestBidder
	}
	return 0
}

func (x *ReplicaUpdate) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *ReplicaUpdate) GetAuctionFinished() bool {
	if x != nil {
		return x.AuctionFinished
	}
	return false
}

func (x *ReplicaUpdate) GetRequestIdentifier() int64 {
	if x != nil {
		return x.RequestIdentifier
	}
	return 0
}

func (x *ReplicaUpdate) GetResponse() *BidAck {
	if x != nil {
		return x.Response
	}
	return nil
}

type ReplicaIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaIdentity) Reset() {
	*x = ReplicaIdentity{}
	mi := &file_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaIdentity) ProtoMessage() {}

func (x *ReplicaIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaIdentity.ProtoReflect.Descriptor instead.
func (*ReplicaIdentity) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{5}
}

func (x *ReplicaIdentity) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReplicaIdentity) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ReplicaState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Identity        *ReplicaIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	HighestBidder   int64                  `protobuf:"varint,2,opt,name=highest_bidder,json=highestBidder,proto3" json:"highest_bidder,omitempty"`
	HighestBid      int64                  `protobuf:"varint,3,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	AuctionFinished bool                   `protobuf:"varint,4,opt,name=auction_finished,json=auctionFinished,proto3" json:"auction_finished,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReplicaState) Reset() {
	*x = ReplicaState{}
	mi := &file_proto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaState) ProtoMessage() {}

func (x *ReplicaState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaState.ProtoReflect.Descriptor instead.
func (*ReplicaState) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{6}
}

func (x *ReplicaState) GetIdentity() *ReplicaIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ReplicaState) GetHighestBidder() int64 {
	if x != nil {
		return x.HighestBidder
	}
	return 0
}

func (x *ReplicaState) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *ReplicaState) GetAuctionFinished() bool {
	if x != nil {
		return x.AuctionFinished
	}
	return false
}

type ElectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderGreater bool                   `protobuf:"varint,1,opt,name=sender_greater,json=senderGreater,proto3" json:"sender_greater,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElectionResponse) Reset() {
	*x = ElectionResponse{}
	mi := &file_proto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionResponse) ProtoMessage() {}

func (x *ElectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionResponse.ProtoReflect.Descriptor instead.
func (*ElectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{7}
}

func (x *ElectionResponse) GetSenderGreater() bool {
	if x != nil {
		return x.SenderGreater
	}
	return false
}

type Leader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leader) Reset() {
	*x = Leader{}
	mi := &file_proto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leader) ProtoMessage() {}

func (x *Leader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leader.ProtoReflect.Descriptor instead.
func (*Leader) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{8}
}

func (x *Leader) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\"X\n" +
	"\tBidAmount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"bid_amount\x18\x03 \x01(\x03R\tbidAmount\"B\n" +
	"\x06BidAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"f\n" +
	"\rAuctionResult\x12\x1f\n" +
	"\vhighest_bid\x18\x01 \x01(\x03R\n" +
	"highestBid\x12\x16\n" +
	"\x06winner\x18\x02 \x01(\x03R\x06winner\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\a\n" +
	"\x05Empty\"\xf4\x01\n" +
	"\rReplicaUpdate\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12%\n" +
	"\x0ehighest_bidder\x18\x02 \x01(\x03R\rhighestBidder\x12\x1f\n" +
	"\vhighest_bid\x18\x03 \x01(\x03R\n" +
	"highestBid\x12)\n" +
	"\x10auction_finished\x18\x04 \x01(\bR\x0fauctionFinished\x12-\n" +
	"\x12request_identifier\x18\x05 \x01(\x03R\x11requestIdentifier\x12#\n" +
	"\bresponse\x18\x06 \x01(\v2\a.BidAckR\bresponse\"?\n" +
	"\x0fReplicaIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\xaf\x01\n" +
	"\fReplicaState\x12,\n" +
	"\bidentity\x18\x01 \x01(\v2\x10.ReplicaIdentityR\bidentity\x12%\n" +
	"\x0ehighest_bidder\x18\x02 \x01(\x03R\rhighestBidder\x12\x1f\n" +
	"\vhighest_bid\x18\x03 \x01(\x03R\n" +
	"highestBid\x12)\n" +
	"\x10auction_finished\x18\x04 \x01(\bR\x0fauctionFinished\"9\n" +
	"\x10ElectionResponse\x12%\n" +
	"\x0esender_greater\x18\x01 \x01(\bR\rsenderGreater\"\x18\n" +
	"\x06Leader\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2G\n" +
	"\aAuction\x12\x1a\n" +
	"\x03Bid\x12\n" +
	".BidAmount\x1a\a.BidAck\x12 \n" +
	"\x06Result\x12\x06.Empty\x1a\x0e.AuctionResult2\x8c\x01\n" +
	"\aReplica\x12\x1f\n" +
	"\x06Update\x12\r.ReplicaState\x1a\x06.Empty\x124\n" +
	"\rStartElection\x12\x10.ReplicaIdentity\x1a\x11.ElectionResponse\x12*\n" +
	"\x10ElectionFinished\x12\a.Leader\x1a\r.ReplicaStateB\x0eZ\fauction/grpcb\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_proto_goTypes = []any{
	(*BidAmount)(nil),        // 0: BidAmount
	(*BidAck)(nil),           // 1: BidAck
	(*AuctionResult)(nil),    // 2: AuctionResult
	(*Empty)(nil),            // 3: Empty
	(*ReplicaUpdate)(nil),    // 4: ReplicaUpdate
	(*ReplicaIdentity)(nil),  // 5: ReplicaIdentity
	(*ReplicaState)(nil),     // 6: ReplicaState
	(*ElectionResponse)(nil), // 7: ElectionResponse
	(*Leader)(nil),           // 8: Leader
}
var file_proto_proto_depIdxs = []int32{
	1, // 0: ReplicaUpdate.response:type_name -> BidAck
	5, // 1: ReplicaState.identity:type_name -> ReplicaIdentity
	0, // 2: Auction.Bid:input_type -> BidAmount
	3, // 3: Auction.Result:input_type -> Empty
	6, // 4: Replica.Update:input_type -> ReplicaState
	5, // 5: Replica.StartElection:input_type -> ReplicaIdentity
	8, // 6: Replica.ElectionFinished:input_type -> Leader
	1, // 7: Auction.Bid:output_type -> BidAck
	2, // 8: Auction.Result:output_type -> AuctionResult
	3, // 9: Replica.Update:output_type -> Empty
	7, // 10: Replica.StartElection:output_type -> ElectionResponse
	6, // 11: Replica.ElectionFinished:output_type -> ReplicaState
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
